-- liquibase formatted sql
-- state: 1
-- changeset liquibase: 1
----------------------------------------------------------------------------------------------
-- CREATE tables: person, tourist_package, reservation, destination

CREATE TABLE
    IF NOT EXISTS public.person (
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (
            INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1
        ),
        name VARCHAR(255),
        email VARCHAR(255),
        document_number VARCHAR(255),
        address CHARACTER VARYING,
        phone_number VARCHAR(255),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        deleted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT person_pkey PRIMARY KEY (id)
    );

CREATE TABLE
    IF NOT EXISTS public.tourist_package (
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (
            INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1
        ),
        name VARCHAR(255),
        date TIMESTAMP,
        time varchar(255),
        price DOUBLE PRECISION,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        deleted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT tourist_package_pkey PRIMARY KEY (id)
    );

CREATE TABLE
    IF NOT EXISTS public.reservation (
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (
            INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1
        ),
        date_reservation TIMESTAMP,
        amount_people INTEGER,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        deleted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        person_id INTEGER,
        tourist_package INTEGER,
        CONSTRAINT reservation_pkey PRIMARY KEY (id),
        CONSTRAINT person_id_fk FOREIGN KEY (person_id)
        REFERENCES public.person (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
        CONSTRAINT tourist_package_fk FOREIGN KEY (tourist_package)
        REFERENCES public.tourist_package (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
    );

CREATE TABLE
    IF NOT EXISTS public.destination (
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (
            INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1
        ),
        value VARCHAR(255),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        deleted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        tourist_package_id INTEGER,
        CONSTRAINT destination_pkey PRIMARY KEY (id),
        CONSTRAINT tourist_package_destination_fk FOREIGN KEY (tourist_package_id)
        REFERENCES public.tourist_package (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
    );